{% set version = "1.35.0" %}

package:
  name: deno
  version: {{ version }}

source:
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno_src.tar.gz  # [not osx or not arm64]
    sha256: 8e3f2a31e05156be4ad57559ad1de1feb4c6261fb7f7e3510ba3adb50925c987  # [not osx or not arm64]
    patches:        # [not osx or not arm64]
      - fix-libffi-msvc.patch     # [not osx or not arm64]
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno-aarch64-apple-darwin.zip  # [osx and arm64]
    sha256: 19649d3ab600b564c346d3f963c7aca9c1f922715684d46577ae09a1718bb217  # [osx and arm64]

build:
  number: 0

requirements:   # [not osx or not arm64]
  build:   # [not osx or not arm64]
    - {{ compiler("rust") }}   # [not osx or not arm64]
    # needs c compiler for run_exports
    - {{ compiler("c") }}      # [not osx or not arm64]
    # for some reason, test_ffi pkg needs lld on osx-arm64
    # - lld    # [osx and arm64]
    - cargo-bundle-licenses   # [not osx or not arm64]
    - make   # [unix and not arm64]
  run:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]

test:
  commands:
    - deno --help
    - deno run https://deno.land/std/examples/welcome.ts
    - if [ "$DENO_INSTALL_ROOT" != "$PREFIX" ]; then echo "DENO_INTALL_ROOT var not set correctly" && exit 1; fi    # [unix]
    - IF "%DENO_INSTALL_ROOT:/=\%" NEQ "%PREFIX:/=\%\Library" exit 1    # [win]

about:
  home: https://deno.land
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.md    # [not osx or not arm64]
    - DENO_THIRDPARTY_LICENSES.yml    # [not osx or not arm64]
    # the binary doesn't ship with a license. This is one taken from the github repo.
    - LICENSE    # [osx and arm64]
  summary: A simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust
  doc_url: https://deno.land/manual
  dev_url: https://github.com/denoland/deno

extra:
  recipe-maintainers:
    - mdekstrand
    - cderv
    - cscheid
    - dragonstyle
    - msarahan
