build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
idle_timeout_minutes: 60
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_build:
  pkg_format: '2'
